### ISSUE TITLE
Make PIP aware of exists of opencv-python, and not to install it again

### ISSUE THREAD

**Issue by DIYer22** [gigante/python-opencv#2]
When build new docker image based on `dkimg/opencv:4.5.4-ubuntu`
```docker
FROM dkimg/opencv:4.5.4-ubuntu
RUN pip install -r requirements.txt
```
If `opencv-python` or `opencv-contrib-python` in `requirements.txt` or in some dependencies, pip will install it again. then bad things happen.

```bash
root@4ff7b7682ce4:/opt/build# pip install opencv-python
Collecting opencv-python
  Downloading opencv_python-4.5.5.64-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.5 MB)
     |████████████████████████████████| 60.5 MB 141 kB/s 
Requirement already satisfied: numpy>=1.17.3 in /usr/lib/python3/dist-packages (from opencv-python) (1.19.5)
Installing collected packages: opencv-python
Successfully installed opencv-python-4.5.5.64

root@4ff7b7682ce4:/opt/build# python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by DIYer22** [comment]
I have fixed the issue by:
`pip3 install --no-cache-dir opencv-python opencv-contrib-python` and manual rm `cv2` before `make install`
```docker
    && make -j$(nproc) \
    && echo "Make pip aware of exists of opencv-python!" \
    && pip3 install --no-cache-dir opencv-python opencv-contrib-python  \
    && rm /usr/local/lib/python3.9/*-packages/cv2 /usr/local/lib/python3.9/*-packages/*_python.libs -r \
    && make install\
```

**Comment by DIYer22** [comment]
I modified Dockerfile with those differences:
- No more repeated installation of opencv-python or opencv-contrib-python
- More popular and mature Python version


See here: https://github.com/DIYer22/tiny_cv2.docker

**Comment by gigante** [comment]
This image was made from the build of opencv + contrib. No need to install packages via pip.

I would recommend using the image as is OR the python packages.

If the problem is size, you can use the version with alpine (130 MB)

Thanks for the contribution :)
